language: go
go:
  - "1.10.x"

addons:
  apt:
    packages:
      - make
      - tree

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  - cd ${TRAVIS_BUILD_DIR}

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  fqdn: 3peakslogistics.com
  repo: 3peakslogistics/3peakslogistics.github.io
  committer-from-gh: true
  target-branch: master
  verbose: true
  on:
    branch: master