# Site settings
baseurl = "https://3peakslogistics.com"
languageCode = "en-us"
title = "3 Peaks Logistics"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  name = "3 Peaks Logistics"
  description = "A premier transportation and freight logistics company in the Pacific Northwest"
  email = "dispatch@3peakslogistics.com"

  # Link custom assets relative to /static
  custom_css = [
    "/css/3pl.css",
  ]
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation
  [params.navigation]
    brand = "3 Peaks Logistics"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    about = "About"
    services = "Services"
    contact = "Contact"

  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = ""
    subtitle = "3 Peaks Logistics"
    buttonText = "Tell me more"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-truck"
      title = "Truckload"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-truck"
      title = "Less Than Truckload"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-truck"
      title = "Regrigerated"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-truck"
      title = "Van"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-truck"
      title = "Flatbed"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    [[params.services.row.list]]
      icon = "fa-truck"
      title = "Stepdeck"
      description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
      url = "#"

    # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = "Lorem ipsum dolor sit amet consectetur."

  # Contact section
  [params.contact]
    enable = true
    title = "Contact us"
    subtitle  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"
    email = "dispatch@3peakslogistics.com"

    [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0."

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"